name: Conformance

on:
  pull_request:
    types: [opened, synchronize, edited]

---
steps:
  - name: PR title is valid
    if: >
      startsWith(github.event.pull_request.title, 'ğŸ“¦ ') ||
      startsWith(github.event.pull_request.title, 'ğŸ› ') ||
      startsWith(github.event.pull_request.title, 'ğŸ‘Œ ') ||
      startsWith(github.event.pull_request.title, 'ğŸš€ ') ||
      startsWith(github.event.pull_request.title, 'â€¼ï¸ ') ||
      startsWith(github.event.pull_request.title, 'â¬†ï¸ ')
    run: |
      echo 'Title checks passed'
